# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-23 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='desc',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tag',
            field=models.CharField(default='', max_length=30),
        ),
    ]
