# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-23 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitapp', '0002_auto_20191123_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tag',
            field=models.CharField(choices=[('movies', 'movies'), ('food', 'food'), ('housing', 'housing'), ('travel', 'travel'), ('others', 'others')], default='others', max_length=30),
        ),
    ]
