# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-24 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitapp', '0003_auto_20191123_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
