# Generated by Django 2.2.6 on 2019-11-24 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splitapp', '0004_auto_20191124_1422'),
        ('splitapp', '0004_auto_20191124_0956'),
    ]

    operations = [
    ]
