# Generated by Django 2.2.6 on 2019-11-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitapp', '0005_merge_20191124_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('activity_desc', models.TextField(blank=True, default='', null=True)),
            ],
            options={
                'db_table': 'activity',
            },
        ),
    ]
